# Generated by Django 3.2.12 on 2022-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('song_id', models.IntegerField()),
                ('sender', models.CharField(max_length=200)),
                ('recipient', models.CharField(max_length=200)),
            ],
        ),
    ]
