# Generated by Django 3.2.12 on 2022-03-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
