# Generated by Django 3.2.12 on 2022-03-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0005_auto_20220306_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
