# Generated by Django 3.2.12 on 2022-03-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0007_alter_message_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='song_id',
        ),
        migrations.AddField(
            model_name='message',
            name='track_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
