# Generated by Django 3.2.12 on 2022-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0010_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
