# Generated by Django 3.2.12 on 2022-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0012_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
